---
title: "Correlation analysis of Arcuate Nucleus/Median Eminence astrocytes dataset from Lutomska LM et al 2022"
author: "Evgenii O. Tretiakov"
date: "`r Sys.Date()`"
format:
  html:
    toc: true
    df-print: paged
    code-fold: true
    fig-width: 14
    fig-height: 12
    fig-format: retina
    fig-responsive: true
    fig-dpi: 600
execute:
  keep-md: false
  echo: true
  error: false
  message: false
  warning: false
  debug: false
knitr:
  opts_chunk:
    autodep: true
    fig.align: center
    fig.retina: 2
    fig.width: 14
    fig.height: 12
---

```{r setup, include = FALSE}
DOCNAME <- "correlations-within-astrocytes-dataset-from-lutomska-2022"
NOW <- Sys.time()

# Time chunks during knitting
knitr::knit_hooks$set(timeit = function(before) {
  if (before) {
    print(paste("Start:", Sys.time()))
    NOW <<- Sys.time()
  } else {
    print(paste("Stop:", Sys.time()))
    print(Sys.time() - NOW)
  }
})

knitr::knit_hooks$set(debug = function(before, options, envir) {
  if (!before) {
    message(
      paste(names(envir), as.list(envir),
        sep = " = ", collapse = "\n"
      )
    )
  }
})

knitr::opts_chunk$set(
  cache          = FALSE,
  dev            = c("png", "pdf"),
  timeit         = TRUE
)
```

## Load data and setup parameters

```{r libraries, cache=FALSE}
# Load tidyverse infrastructure packages
suppressPackageStartupMessages({
  library(future)
  library(here)
  library(tidyverse)
  library(magrittr)
  library(stringr)
  library(skimr)
  library(RColorBrewer)
})


# Load packages for scRNA-seq analysis and visualisation
suppressPackageStartupMessages({
  library(ggplot2)
  library(cowplot)
  library(patchwork)
  library(ggstatsplot)
  library(anndata)
  library(sceasy)
})

sc <- import('scanpy', convert = FALSE)
```

### Set paths

```{r paths}
src_dir <- here("code")
data_dir <- here("data")
output_dir <- here("output")
plots_dir <- here(output_dir, "figures")
tables_dir <- here(output_dir, "tables")
```

### Load helper functions and gene-sets

```{r source, cache = FALSE}
source(here(src_dir, "genes.R"))
source(here(src_dir, "functions.R"))
```

### Set fixed variables

```{r params-computation, cache = FALSE}
# set seed
reseed <- 42
set.seed(seed = reseed)

# Parameters for parallel execution
n_cores <- 32
plan("multisession", workers = n_cores)
options(
  future.globals.maxSize = 100000 * 1024^2,
  future.rng.onMisuse = "ignore"
)
plan()


# ggplot2 theme
theme_set(ggmin::theme_powerpoint())
```

```{r params}
bioproject <- "PRJNA847050"
project <- "lutomska2022-Arc"
cb_fpr <- 0.001
low_cutoff_gene <- 500
high_cutoff_gene <- NULL
high_cutoff_gene <- 10000
low_cutoff_umis <- NULL
low_cutoff_umis <- -Inf
high_cutoff_umis <- 45000
high_cutoff_pc_mt <- 25
high_cutoff_pc_ribo <- 20
high_cutoff_pc_hb <- 0.1
high_cutoff_doublet_score <- 0.33
high_cutoff_complexity <- 0.8
```

## Load selected astrocytes data from Lutomska LM et al (2022)

```{r load-data, cache = FALSE}
anndata <- sc$read(here(
  data_dir,
  sprintf("class_cello/%s-astrocytes_dataset-%s-initial_selection.h5ad", bioproject, cb_fpr)))
```

### Convert adata object to R AnnDataR6 object.
```{r convert-to-seurat}
adata <- py_to_r(anndata)
# X_norm <- sc$pp$normalize_total(adata, target_sum = 1e+04, inplace = FALSE)["X"]
sc$pp$normalize_total(adata, target_sum = 1e+04, inplace = TRUE)
sc$pp$log1p(adata)
class(adata)
class(adata$X)
adata
```

```{r export-expression}
exp_mtx_fname <- here(
  data_dir,
  sprintf("%s-astrocytes_dataset-%s-expr-mtx.csv", bioproject, cb_fpr)
)
exp_tsv_fname <- here(
  data_dir,
  sprintf("%s-astrocytes_dataset-%s-expr-mtx.tsv", bioproject, cb_fpr)
)
X <- as.data.frame(as.matrix(adata$X))
expr_data <- as.data.frame(t(X))
colnames(expr_data) <- rownames(adata$X)
rownames(expr_data) <- colnames(adata$X)
readr::write_csv(X, file = exp_mtx_fname)
readr::write_tsv(expr_data, file = exp_tsv_fname)
```

```{r select-features}
# X <- as.data.frame(py_to_r(X_norm))
# colnames(X) <- colnames(adata$X)
X <- X[, c(npr, nmr, genes.embed) %>% .[. %in% colnames(X)]]
X <- X[, colSums(X) > 0]
```

```{r metadata}
cdata <- as.data.frame(adata$obs)
```

```{r merge-data}
df <- cbind(cdata, X)
glimpse(df)
```

```{r }
p_corrs <- list(
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Adcyap1r1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Cckar, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Cckbr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Cntfr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Crhr1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Esr1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Galr2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Ghr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gpr83, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Grpr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Hcrtr2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Kiss1r, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Mc1r, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Mc3r, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Mc4r, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Nmbr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Nmur1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Nmur2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Npffr1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Npffr2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Npy1r, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Npy2r, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Npy5r, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Ntrk2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Ntsr2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Oprk1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Oprm1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Oxtr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Prlhr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Prlr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Sstr1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Sstr2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Sstr3, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Tacr1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Tacr3, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Trhr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Vipr1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Vipr2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gria1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gria2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gria3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gria4,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Grid1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Grid2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Grik1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Grik2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Grik3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Grik4,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Grik5,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Grin1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Grin2a,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Grin2b,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Grin2c,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Grin2d,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Grin3a,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Grin3b,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Grm1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Grm5,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Grm2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Grm3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Grm4,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Grm7,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Grm8,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gabra1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gabra2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gabra3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gabra4,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gabra5,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gabra6,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gabrb1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gabrb2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gabrb3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gabrg1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gabrg2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gabrg3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gabrd,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gabre,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gabrq,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gabrr2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gabrr3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gabbr1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gabbr2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Drd2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Drd3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Htr1b,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Htr1f,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Htr2a,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Htr2b,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Htr2c,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Htr3b,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Htr4,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Htr5a,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Htr5b,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Htr6,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Htr7,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gnai1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gnai2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gnai3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gnao1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gnaz,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Abcd1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Abcd2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Abcd3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Acaa2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Acox1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Agt,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Aldh1a1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Aldh1l1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Aldoc,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Apoe,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Aqp4,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Ckb,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Cnr2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Cst3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Dagla,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Daglb,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Decr2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Dnm1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Ech1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Egfr,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Eno1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Faah,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Fgfr3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Fis1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Fos,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "springgreen"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Fth1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Ftl1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gfap,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "limegreen"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gja1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Gli1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Glul,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Hacd2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Hadhb,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Hepacam,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Htra1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Lcat,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Lpcat3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Lxn,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "magenta"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Mfn1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Mgll,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Mief1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Napepld,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Ndrg2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Nfia,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Opa1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Pex1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Pex10,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Pex12,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Pex13,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Pex14,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Pex16,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Pex2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Pex26,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Pex3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Pex6,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Pla2g7,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Plcb1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Pygb,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = S100a6,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = S100b,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Scd2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Sgcd,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Slc1a2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Slc1a3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Slc38a1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Slc6a11,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Slit1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Slit2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Sox9,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Tafa1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Mfn2,  y = Tkt,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow",    yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Adcyap1r1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "yellow", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Cckar, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Cckbr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Cntfr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Crhr1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Esr1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Galr2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Ghr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gpr83, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Grpr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Hcrtr2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Kiss1r, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Mc1r, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Mc3r, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Mc4r, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Nmbr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Nmur1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Nmur2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Npffr1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Npffr2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Npy1r, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Npy2r, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Npy5r, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Ntrk2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Ntsr2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Oprk1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Oprm1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Oxtr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Prlhr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Prlr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Sstr1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Sstr2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Sstr3, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Tacr1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Tacr3, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Trhr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Vipr1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Vipr2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gria1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gria2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gria3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gria4,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Grid1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Grid2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Grik1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Grik2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Grik3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Grik4,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Grik5,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Grin1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Grin2a,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Grin2b,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Grin2c,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Grin2d,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Grin3a,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Grin3b,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Grm1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Grm5,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Grm2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Grm3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Grm4,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Grm7,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Grm8,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gabra1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gabra2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gabra3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gabra4,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gabra5,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gabra6,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gabrb1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gabrb2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gabrb3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gabrg1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gabrg2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gabrg3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gabrd,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gabre,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gabrq,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gabrr2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gabrr3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gabbr1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gabbr2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Drd2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Drd3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Htr1b,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Htr1f,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Htr2a,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Htr2b,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Htr2c,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Htr3b,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Htr4,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Htr5a,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Htr5b,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Htr6,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Htr7,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gnai1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gnai2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gnai3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gnao1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gnaz,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Abcd1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Abcd2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Abcd3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Acaa2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Acox1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Agt,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Aldh1a1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Aldh1l1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Aldoc,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Apoe,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Aqp4,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Ckb,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Cnr2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Cst3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Dagla,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Daglb,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Decr2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Dnm1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Ech1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Egfr,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Eno1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Faah,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Fgfr3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Fis1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Fos,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "springgreen"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Fth1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Ftl1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gfap,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "limegreen"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gja1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Gli1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Glul,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Hacd2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Hadhb,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Hepacam,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Htra1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Lcat,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Lpcat3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Mfn1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Mfn2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "yellow"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Mgll,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Mief1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Napepld,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Ndrg2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Nfia,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Opa1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Pex1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Pex10,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Pex12,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Pex13,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Pex14,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Pex16,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Pex2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Pex26,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Pex3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Pex6,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Pla2g7,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Plcb1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Pygb,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = S100a6,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = S100b,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Scd2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Sgcd,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Slc1a2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Slc1a3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Slc38a1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Slc6a11,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Slit1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Slit2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Sox9,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Tafa1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Lxn,  y = Tkt,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "magenta", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Adcyap1r1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Cckar, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Cckbr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Cntfr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Crhr1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Esr1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Galr2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Ghr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gpr83, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Grpr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Hcrtr2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Kiss1r, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Mc1r, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Mc3r, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Mc4r, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Nmbr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Nmur1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Nmur2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Npffr1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Npffr2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Npy1r, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Npy2r, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Npy5r, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Ntrk2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Ntsr2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Oprk1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Oprm1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Oxtr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Prlhr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Prlr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Sstr1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Sstr2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Sstr3, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Tacr1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Tacr3, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Trhr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Vipr1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Vipr2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gria1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gria2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gria3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gria4,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Grid1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Grid2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Grik1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Grik2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Grik3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Grik4,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Grik5,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Grin1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Grin2a,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Grin2b,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Grin2c,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Grin2d,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Grin3a,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Grin3b,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Grm1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Grm5,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Grm2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Grm3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Grm4,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Grm7,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Grm8,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gabra1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gabra2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gabra3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gabra4,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gabra5,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gabra6,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gabrb1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gabrb2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gabrb3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gabrg1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gabrg2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gabrg3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gabrd,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gabre,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gabrq,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gabrr2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gabrr3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gabbr1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gabbr2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Drd2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Drd3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Htr1b,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Htr1f,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Htr2a,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Htr2b,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Htr2c,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Htr3b,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Htr4,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Htr5a,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Htr5b,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Htr6,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Htr7,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gnai1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gnai2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gnai3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gnao1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gnaz,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Abcd1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Abcd2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Abcd3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Acaa2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Acox1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Agt,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Aldh1a1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Aldh1l1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Aldoc,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Apoe,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Aqp4,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Ckb,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Cnr2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Cst3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Dagla,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Daglb,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Decr2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Dnm1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Ech1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Egfr,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Eno1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Faah,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Fgfr3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Fis1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Fos,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "springgreen"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Fth1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Ftl1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gja1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Gli1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Glul,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Hacd2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Hadhb,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Hepacam,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Htra1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Lcat,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Lpcat3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Lxn,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "magenta"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Mfn1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Mfn2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "yellow"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Mgll,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Mief1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Napepld,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Ndrg2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Nfia,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Opa1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Pex1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Pex10,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Pex12,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Pex13,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Pex14,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Pex16,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Pex2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Pex26,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Pex3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Pex6,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Pla2g7,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Plcb1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Pygb,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = S100a6,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = S100b,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Scd2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Sgcd,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Slc1a2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Slc1a3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Slc38a1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Slc6a11,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Slit1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Slit2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Sox9,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Tafa1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Gfap,  y = Tkt,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "limegreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Adcyap1r1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Cckar, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Cckbr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Cntfr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Crhr1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Esr1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Galr2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Ghr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gpr83, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Grpr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Hcrtr2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Kiss1r, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Mc1r, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Mc3r, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Mc4r, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Nmbr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Nmur1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Nmur2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Npffr1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Npffr2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Npy1r, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Npy2r, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Npy5r, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Ntrk2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Ntsr2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Oprk1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Oprm1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Oxtr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Prlhr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Prlr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Sstr1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Sstr2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Sstr3, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Tacr1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Tacr3, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Trhr, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Vipr1, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Vipr2, grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "cyan"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gria1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gria2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gria3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gria4,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Grid1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Grid2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Grik1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Grik2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Grik3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Grik4,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Grik5,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Grin1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Grin2a,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Grin2b,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Grin2c,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Grin2d,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Grin3a,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Grin3b,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Grm1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Grm5,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Grm2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Grm3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Grm4,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Grm7,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Grm8,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gabra1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gabra2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gabra3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gabra4,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gabra5,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gabra6,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gabrb1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gabrb2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gabrb3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gabrg1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gabrg2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gabrg3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gabrd,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gabre,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gabrq,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gabrr2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gabrr3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gabbr1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gabbr2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Drd2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Drd3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Htr1b,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Htr1f,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Htr2a,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Htr2b,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Htr2c,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Htr3b,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Htr4,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Htr5a,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Htr5b,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Htr6,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Htr7,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gnai1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gnai2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gnai3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gnao1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gnaz,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "skyblue"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Abcd1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Abcd2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Abcd3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Acaa2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Acox1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Agt,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Aldh1a1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Aldh1l1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Aldoc,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Apoe,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Aqp4,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Ckb,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Cnr2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Cst3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Dagla,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Daglb,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Decr2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Dnm1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Ech1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Egfr,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Eno1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Faah,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Fgfr3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Fis1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Fth1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Ftl1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gfap,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "limegreen"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gja1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Gli1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Glul,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Hacd2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Hadhb,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Hepacam,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Htra1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Lcat,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Lpcat3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Lxn,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "magenta"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Mfn1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Mfn2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "yellow"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Mgll,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Mief1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Napepld,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Ndrg2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Nfia,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Opa1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Pex1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Pex10,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Pex12,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Pex13,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Pex14,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Pex16,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Pex2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Pex26,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Pex3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Pex6,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Pla2g7,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Plcb1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Pygb,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = S100a6,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = S100b,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Scd2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Sgcd,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Slc1a2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Slc1a3,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Slc38a1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Slc6a11,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Slit1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Slit2,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Sox9,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Tafa1,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid"),
    grouped_ggscatterstats(df, type = "r", x = Fos,  y = Tkt,  grouping.var = expbtch, plotgrid.args = list(nrow = 3, ncol = 1), point.label.args = list(alpha = 0.7, size = 4, color = "grey50"), xfill = "springgreen", yfill = "orchid")
)
n_corrs <- list(
    "arc-lutomska2022-log1pnorm-Mfn2-Adcyap1r1",
    "arc-lutomska2022-log1pnorm-Mfn2-Cckar",
    "arc-lutomska2022-log1pnorm-Mfn2-Cckbr",
    "arc-lutomska2022-log1pnorm-Mfn2-Cntfr",
    "arc-lutomska2022-log1pnorm-Mfn2-Crhr1",
    "arc-lutomska2022-log1pnorm-Mfn2-Esr1",
    "arc-lutomska2022-log1pnorm-Mfn2-Galr2",
    "arc-lutomska2022-log1pnorm-Mfn2-Ghr",
    "arc-lutomska2022-log1pnorm-Mfn2-Gpr83",
    "arc-lutomska2022-log1pnorm-Mfn2-Grpr",
    "arc-lutomska2022-log1pnorm-Mfn2-Hcrtr2",
    "arc-lutomska2022-log1pnorm-Mfn2-Kiss1r",
    "arc-lutomska2022-log1pnorm-Mfn2-Mc1r",
    "arc-lutomska2022-log1pnorm-Mfn2-Mc3r",
    "arc-lutomska2022-log1pnorm-Mfn2-Mc4r",
    "arc-lutomska2022-log1pnorm-Mfn2-Nmbr",
    "arc-lutomska2022-log1pnorm-Mfn2-Nmur1",
    "arc-lutomska2022-log1pnorm-Mfn2-Nmur2",
    "arc-lutomska2022-log1pnorm-Mfn2-Npffr1",
    "arc-lutomska2022-log1pnorm-Mfn2-Npffr2",
    "arc-lutomska2022-log1pnorm-Mfn2-Npy1r",
    "arc-lutomska2022-log1pnorm-Mfn2-Npy2r",
    "arc-lutomska2022-log1pnorm-Mfn2-Npy5r",
    "arc-lutomska2022-log1pnorm-Mfn2-Ntrk2",
    "arc-lutomska2022-log1pnorm-Mfn2-Ntsr2",
    "arc-lutomska2022-log1pnorm-Mfn2-Oprk1",
    "arc-lutomska2022-log1pnorm-Mfn2-Oprm1",
    "arc-lutomska2022-log1pnorm-Mfn2-Oxtr",
    "arc-lutomska2022-log1pnorm-Mfn2-Prlhr",
    "arc-lutomska2022-log1pnorm-Mfn2-Prlr",
    "arc-lutomska2022-log1pnorm-Mfn2-Sstr1",
    "arc-lutomska2022-log1pnorm-Mfn2-Sstr2",
    "arc-lutomska2022-log1pnorm-Mfn2-Sstr3",
    "arc-lutomska2022-log1pnorm-Mfn2-Tacr1",
    "arc-lutomska2022-log1pnorm-Mfn2-Tacr3",
    "arc-lutomska2022-log1pnorm-Mfn2-Trhr",
    "arc-lutomska2022-log1pnorm-Mfn2-Vipr1",
    "arc-lutomska2022-log1pnorm-Mfn2-Vipr2",
    "arc-lutomska2022-log1pnorm-Mfn2-Gria1",
    "arc-lutomska2022-log1pnorm-Mfn2-Gria2",
    "arc-lutomska2022-log1pnorm-Mfn2-Gria3",
    "arc-lutomska2022-log1pnorm-Mfn2-Gria4",
    "arc-lutomska2022-log1pnorm-Mfn2-Grid1",
    "arc-lutomska2022-log1pnorm-Mfn2-Grid2",
    "arc-lutomska2022-log1pnorm-Mfn2-Grik1",
    "arc-lutomska2022-log1pnorm-Mfn2-Grik2",
    "arc-lutomska2022-log1pnorm-Mfn2-Grik3",
    "arc-lutomska2022-log1pnorm-Mfn2-Grik4",
    "arc-lutomska2022-log1pnorm-Mfn2-Grik5",
    "arc-lutomska2022-log1pnorm-Mfn2-Grin1",
    "arc-lutomska2022-log1pnorm-Mfn2-Grin2a",
    "arc-lutomska2022-log1pnorm-Mfn2-Grin2b",
    "arc-lutomska2022-log1pnorm-Mfn2-Grin2c",
    "arc-lutomska2022-log1pnorm-Mfn2-Grin2d",
    "arc-lutomska2022-log1pnorm-Mfn2-Grin3a",
    "arc-lutomska2022-log1pnorm-Mfn2-Grin3b",
    "arc-lutomska2022-log1pnorm-Mfn2-Grm1",
    "arc-lutomska2022-log1pnorm-Mfn2-Grm5",
    "arc-lutomska2022-log1pnorm-Mfn2-Grm2",
    "arc-lutomska2022-log1pnorm-Mfn2-Grm3",
    "arc-lutomska2022-log1pnorm-Mfn2-Grm4",
    "arc-lutomska2022-log1pnorm-Mfn2-Grm7",
    "arc-lutomska2022-log1pnorm-Mfn2-Grm8",
    "arc-lutomska2022-log1pnorm-Mfn2-Gabra1",
    "arc-lutomska2022-log1pnorm-Mfn2-Gabra2",
    "arc-lutomska2022-log1pnorm-Mfn2-Gabra3",
    "arc-lutomska2022-log1pnorm-Mfn2-Gabra4",
    "arc-lutomska2022-log1pnorm-Mfn2-Gabra5",
    "arc-lutomska2022-log1pnorm-Mfn2-Gabra6",
    "arc-lutomska2022-log1pnorm-Mfn2-Gabrb1",
    "arc-lutomska2022-log1pnorm-Mfn2-Gabrb2",
    "arc-lutomska2022-log1pnorm-Mfn2-Gabrb3",
    "arc-lutomska2022-log1pnorm-Mfn2-Gabrg1",
    "arc-lutomska2022-log1pnorm-Mfn2-Gabrg2",
    "arc-lutomska2022-log1pnorm-Mfn2-Gabrg3",
    "arc-lutomska2022-log1pnorm-Mfn2-Gabrd",
    "arc-lutomska2022-log1pnorm-Mfn2-Gabre",
    "arc-lutomska2022-log1pnorm-Mfn2-Gabrq",
    "arc-lutomska2022-log1pnorm-Mfn2-Gabrr2",
    "arc-lutomska2022-log1pnorm-Mfn2-Gabrr3",
    "arc-lutomska2022-log1pnorm-Mfn2-Gabbr1",
    "arc-lutomska2022-log1pnorm-Mfn2-Gabbr2",
    "arc-lutomska2022-log1pnorm-Mfn2-Drd2",
    "arc-lutomska2022-log1pnorm-Mfn2-Drd3",
    "arc-lutomska2022-log1pnorm-Mfn2-Htr1b",
    "arc-lutomska2022-log1pnorm-Mfn2-Htr1f",
    "arc-lutomska2022-log1pnorm-Mfn2-Htr2a",
    "arc-lutomska2022-log1pnorm-Mfn2-Htr2b",
    "arc-lutomska2022-log1pnorm-Mfn2-Htr2c",
    "arc-lutomska2022-log1pnorm-Mfn2-Htr3b",
    "arc-lutomska2022-log1pnorm-Mfn2-Htr4",
    "arc-lutomska2022-log1pnorm-Mfn2-Htr5a",
    "arc-lutomska2022-log1pnorm-Mfn2-Htr5b",
    "arc-lutomska2022-log1pnorm-Mfn2-Htr6",
    "arc-lutomska2022-log1pnorm-Mfn2-Htr7",
    "arc-lutomska2022-log1pnorm-Mfn2-Gnai1",
    "arc-lutomska2022-log1pnorm-Mfn2-Gnai2",
    "arc-lutomska2022-log1pnorm-Mfn2-Gnai3",
    "arc-lutomska2022-log1pnorm-Mfn2-Gnao1",
    "arc-lutomska2022-log1pnorm-Mfn2-Gnaz",
    "arc-lutomska2022-log1pnorm-Mfn2-Abcd1",
    "arc-lutomska2022-log1pnorm-Mfn2-Abcd2",
    "arc-lutomska2022-log1pnorm-Mfn2-Abcd3",
    "arc-lutomska2022-log1pnorm-Mfn2-Acaa2",
    "arc-lutomska2022-log1pnorm-Mfn2-Acox1",
    "arc-lutomska2022-log1pnorm-Mfn2-Agt",
    "arc-lutomska2022-log1pnorm-Mfn2-Aldh1a1",
    "arc-lutomska2022-log1pnorm-Mfn2-Aldh1l1",
    "arc-lutomska2022-log1pnorm-Mfn2-Aldoc",
    "arc-lutomska2022-log1pnorm-Mfn2-Apoe",
    "arc-lutomska2022-log1pnorm-Mfn2-Aqp4",
    "arc-lutomska2022-log1pnorm-Mfn2-Ckb",
    "arc-lutomska2022-log1pnorm-Mfn2-Cnr2",
    "arc-lutomska2022-log1pnorm-Mfn2-Cst3",
    "arc-lutomska2022-log1pnorm-Mfn2-Dagla",
    "arc-lutomska2022-log1pnorm-Mfn2-Daglb",
    "arc-lutomska2022-log1pnorm-Mfn2-Decr2",
    "arc-lutomska2022-log1pnorm-Mfn2-Dnm1",
    "arc-lutomska2022-log1pnorm-Mfn2-Ech1",
    "arc-lutomska2022-log1pnorm-Mfn2-Egfr",
    "arc-lutomska2022-log1pnorm-Mfn2-Eno1",
    "arc-lutomska2022-log1pnorm-Mfn2-Faah",
    "arc-lutomska2022-log1pnorm-Mfn2-Fgfr3",
    "arc-lutomska2022-log1pnorm-Mfn2-Fis1",
    "arc-lutomska2022-log1pnorm-Mfn2-Fos",
    "arc-lutomska2022-log1pnorm-Mfn2-Fth1",
    "arc-lutomska2022-log1pnorm-Mfn2-Ftl1",
    "arc-lutomska2022-log1pnorm-Mfn2-Gfap",
    "arc-lutomska2022-log1pnorm-Mfn2-Gja1",
    "arc-lutomska2022-log1pnorm-Mfn2-Gli1",
    "arc-lutomska2022-log1pnorm-Mfn2-Glul",
    "arc-lutomska2022-log1pnorm-Mfn2-Hacd2",
    "arc-lutomska2022-log1pnorm-Mfn2-Hadhb",
    "arc-lutomska2022-log1pnorm-Mfn2-Hepacam",
    "arc-lutomska2022-log1pnorm-Mfn2-Htra1",
    "arc-lutomska2022-log1pnorm-Mfn2-Lcat",
    "arc-lutomska2022-log1pnorm-Mfn2-Lpcat3",
    "arc-lutomska2022-log1pnorm-Mfn2-Lxn",
    "arc-lutomska2022-log1pnorm-Mfn2-Mfn1",
    "arc-lutomska2022-log1pnorm-Mfn2-Mgll",
    "arc-lutomska2022-log1pnorm-Mfn2-Mief1",
    "arc-lutomska2022-log1pnorm-Mfn2-Napepld",
    "arc-lutomska2022-log1pnorm-Mfn2-Ndrg2",
    "arc-lutomska2022-log1pnorm-Mfn2-Nfia",
    "arc-lutomska2022-log1pnorm-Mfn2-Opa1",
    "arc-lutomska2022-log1pnorm-Mfn2-Pex1",
    "arc-lutomska2022-log1pnorm-Mfn2-Pex10",
    "arc-lutomska2022-log1pnorm-Mfn2-Pex12",
    "arc-lutomska2022-log1pnorm-Mfn2-Pex13",
    "arc-lutomska2022-log1pnorm-Mfn2-Pex14",
    "arc-lutomska2022-log1pnorm-Mfn2-Pex16",
    "arc-lutomska2022-log1pnorm-Mfn2-Pex2",
    "arc-lutomska2022-log1pnorm-Mfn2-Pex26",
    "arc-lutomska2022-log1pnorm-Mfn2-Pex3",
    "arc-lutomska2022-log1pnorm-Mfn2-Pex6",
    "arc-lutomska2022-log1pnorm-Mfn2-Pla2g7",
    "arc-lutomska2022-log1pnorm-Mfn2-Plcb1",
    "arc-lutomska2022-log1pnorm-Mfn2-Pygb",
    "arc-lutomska2022-log1pnorm-Mfn2-S100a6",
    "arc-lutomska2022-log1pnorm-Mfn2-S100b",
    "arc-lutomska2022-log1pnorm-Mfn2-Scd2",
    "arc-lutomska2022-log1pnorm-Mfn2-Sgcd",
    "arc-lutomska2022-log1pnorm-Mfn2-Slc1a2",
    "arc-lutomska2022-log1pnorm-Mfn2-Slc1a3",
    "arc-lutomska2022-log1pnorm-Mfn2-Slc38a1",
    "arc-lutomska2022-log1pnorm-Mfn2-Slc6a11",
    "arc-lutomska2022-log1pnorm-Mfn2-Slit1",
    "arc-lutomska2022-log1pnorm-Mfn2-Slit2",
    "arc-lutomska2022-log1pnorm-Mfn2-Sox9",
    "arc-lutomska2022-log1pnorm-Mfn2-Tafa1",
    "arc-lutomska2022-log1pnorm-Mfn2-Tkt",
    "arc-lutomska2022-log1pnorm-Lxn-Adcyap1r1",
    "arc-lutomska2022-log1pnorm-Lxn-Cckar",
    "arc-lutomska2022-log1pnorm-Lxn-Cckbr",
    "arc-lutomska2022-log1pnorm-Lxn-Cntfr",
    "arc-lutomska2022-log1pnorm-Lxn-Crhr1",
    "arc-lutomska2022-log1pnorm-Lxn-Esr1",
    "arc-lutomska2022-log1pnorm-Lxn-Galr2",
    "arc-lutomska2022-log1pnorm-Lxn-Ghr",
    "arc-lutomska2022-log1pnorm-Lxn-Gpr83",
    "arc-lutomska2022-log1pnorm-Lxn-Grpr",
    "arc-lutomska2022-log1pnorm-Lxn-Hcrtr2",
    "arc-lutomska2022-log1pnorm-Lxn-Kiss1r",
    "arc-lutomska2022-log1pnorm-Lxn-Mc1r",
    "arc-lutomska2022-log1pnorm-Lxn-Mc3r",
    "arc-lutomska2022-log1pnorm-Lxn-Mc4r",
    "arc-lutomska2022-log1pnorm-Lxn-Nmbr",
    "arc-lutomska2022-log1pnorm-Lxn-Nmur1",
    "arc-lutomska2022-log1pnorm-Lxn-Nmur2",
    "arc-lutomska2022-log1pnorm-Lxn-Npffr1",
    "arc-lutomska2022-log1pnorm-Lxn-Npffr2",
    "arc-lutomska2022-log1pnorm-Lxn-Npy1r",
    "arc-lutomska2022-log1pnorm-Lxn-Npy2r",
    "arc-lutomska2022-log1pnorm-Lxn-Npy5r",
    "arc-lutomska2022-log1pnorm-Lxn-Ntrk2",
    "arc-lutomska2022-log1pnorm-Lxn-Ntsr2",
    "arc-lutomska2022-log1pnorm-Lxn-Oprk1",
    "arc-lutomska2022-log1pnorm-Lxn-Oprm1",
    "arc-lutomska2022-log1pnorm-Lxn-Oxtr",
    "arc-lutomska2022-log1pnorm-Lxn-Prlhr",
    "arc-lutomska2022-log1pnorm-Lxn-Prlr",
    "arc-lutomska2022-log1pnorm-Lxn-Sstr1",
    "arc-lutomska2022-log1pnorm-Lxn-Sstr2",
    "arc-lutomska2022-log1pnorm-Lxn-Sstr3",
    "arc-lutomska2022-log1pnorm-Lxn-Tacr1",
    "arc-lutomska2022-log1pnorm-Lxn-Tacr3",
    "arc-lutomska2022-log1pnorm-Lxn-Trhr",
    "arc-lutomska2022-log1pnorm-Lxn-Vipr1",
    "arc-lutomska2022-log1pnorm-Lxn-Vipr2",
    "arc-lutomska2022-log1pnorm-Lxn-Gria1",
    "arc-lutomska2022-log1pnorm-Lxn-Gria2",
    "arc-lutomska2022-log1pnorm-Lxn-Gria3",
    "arc-lutomska2022-log1pnorm-Lxn-Gria4",
    "arc-lutomska2022-log1pnorm-Lxn-Grid1",
    "arc-lutomska2022-log1pnorm-Lxn-Grid2",
    "arc-lutomska2022-log1pnorm-Lxn-Grik1",
    "arc-lutomska2022-log1pnorm-Lxn-Grik2",
    "arc-lutomska2022-log1pnorm-Lxn-Grik3",
    "arc-lutomska2022-log1pnorm-Lxn-Grik4",
    "arc-lutomska2022-log1pnorm-Lxn-Grik5",
    "arc-lutomska2022-log1pnorm-Lxn-Grin1",
    "arc-lutomska2022-log1pnorm-Lxn-Grin2a",
    "arc-lutomska2022-log1pnorm-Lxn-Grin2b",
    "arc-lutomska2022-log1pnorm-Lxn-Grin2c",
    "arc-lutomska2022-log1pnorm-Lxn-Grin2d",
    "arc-lutomska2022-log1pnorm-Lxn-Grin3a",
    "arc-lutomska2022-log1pnorm-Lxn-Grin3b",
    "arc-lutomska2022-log1pnorm-Lxn-Grm1",
    "arc-lutomska2022-log1pnorm-Lxn-Grm5",
    "arc-lutomska2022-log1pnorm-Lxn-Grm2",
    "arc-lutomska2022-log1pnorm-Lxn-Grm3",
    "arc-lutomska2022-log1pnorm-Lxn-Grm4",
    "arc-lutomska2022-log1pnorm-Lxn-Grm7",
    "arc-lutomska2022-log1pnorm-Lxn-Grm8",
    "arc-lutomska2022-log1pnorm-Lxn-Gabra1",
    "arc-lutomska2022-log1pnorm-Lxn-Gabra2",
    "arc-lutomska2022-log1pnorm-Lxn-Gabra3",
    "arc-lutomska2022-log1pnorm-Lxn-Gabra4",
    "arc-lutomska2022-log1pnorm-Lxn-Gabra5",
    "arc-lutomska2022-log1pnorm-Lxn-Gabra6",
    "arc-lutomska2022-log1pnorm-Lxn-Gabrb1",
    "arc-lutomska2022-log1pnorm-Lxn-Gabrb2",
    "arc-lutomska2022-log1pnorm-Lxn-Gabrb3",
    "arc-lutomska2022-log1pnorm-Lxn-Gabrg1",
    "arc-lutomska2022-log1pnorm-Lxn-Gabrg2",
    "arc-lutomska2022-log1pnorm-Lxn-Gabrg3",
    "arc-lutomska2022-log1pnorm-Lxn-Gabrd",
    "arc-lutomska2022-log1pnorm-Lxn-Gabre",
    "arc-lutomska2022-log1pnorm-Lxn-Gabrq",
    "arc-lutomska2022-log1pnorm-Lxn-Gabrr2",
    "arc-lutomska2022-log1pnorm-Lxn-Gabrr3",
    "arc-lutomska2022-log1pnorm-Lxn-Gabbr1",
    "arc-lutomska2022-log1pnorm-Lxn-Gabbr2",
    "arc-lutomska2022-log1pnorm-Lxn-Drd2",
    "arc-lutomska2022-log1pnorm-Lxn-Drd3",
    "arc-lutomska2022-log1pnorm-Lxn-Htr1b",
    "arc-lutomska2022-log1pnorm-Lxn-Htr1f",
    "arc-lutomska2022-log1pnorm-Lxn-Htr2a",
    "arc-lutomska2022-log1pnorm-Lxn-Htr2b",
    "arc-lutomska2022-log1pnorm-Lxn-Htr2c",
    "arc-lutomska2022-log1pnorm-Lxn-Htr3b",
    "arc-lutomska2022-log1pnorm-Lxn-Htr4",
    "arc-lutomska2022-log1pnorm-Lxn-Htr5a",
    "arc-lutomska2022-log1pnorm-Lxn-Htr5b",
    "arc-lutomska2022-log1pnorm-Lxn-Htr6",
    "arc-lutomska2022-log1pnorm-Lxn-Htr7",
    "arc-lutomska2022-log1pnorm-Lxn-Gnai1",
    "arc-lutomska2022-log1pnorm-Lxn-Gnai2",
    "arc-lutomska2022-log1pnorm-Lxn-Gnai3",
    "arc-lutomska2022-log1pnorm-Lxn-Gnao1",
    "arc-lutomska2022-log1pnorm-Lxn-Gnaz",
    "arc-lutomska2022-log1pnorm-Lxn-Abcd1",
    "arc-lutomska2022-log1pnorm-Lxn-Abcd2",
    "arc-lutomska2022-log1pnorm-Lxn-Abcd3",
    "arc-lutomska2022-log1pnorm-Lxn-Acaa2",
    "arc-lutomska2022-log1pnorm-Lxn-Acox1",
    "arc-lutomska2022-log1pnorm-Lxn-Agt",
    "arc-lutomska2022-log1pnorm-Lxn-Aldh1a1",
    "arc-lutomska2022-log1pnorm-Lxn-Aldh1l1",
    "arc-lutomska2022-log1pnorm-Lxn-Aldoc",
    "arc-lutomska2022-log1pnorm-Lxn-Apoe",
    "arc-lutomska2022-log1pnorm-Lxn-Aqp4",
    "arc-lutomska2022-log1pnorm-Lxn-Ckb",
    "arc-lutomska2022-log1pnorm-Lxn-Cnr2",
    "arc-lutomska2022-log1pnorm-Lxn-Cst3",
    "arc-lutomska2022-log1pnorm-Lxn-Dagla",
    "arc-lutomska2022-log1pnorm-Lxn-Daglb",
    "arc-lutomska2022-log1pnorm-Lxn-Decr2",
    "arc-lutomska2022-log1pnorm-Lxn-Dnm1",
    "arc-lutomska2022-log1pnorm-Lxn-Ech1",
    "arc-lutomska2022-log1pnorm-Lxn-Egfr",
    "arc-lutomska2022-log1pnorm-Lxn-Eno1",
    "arc-lutomska2022-log1pnorm-Lxn-Faah",
    "arc-lutomska2022-log1pnorm-Lxn-Fgfr3",
    "arc-lutomska2022-log1pnorm-Lxn-Fis1",
    "arc-lutomska2022-log1pnorm-Lxn-Fos",
    "arc-lutomska2022-log1pnorm-Lxn-Fth1",
    "arc-lutomska2022-log1pnorm-Lxn-Ftl1",
    "arc-lutomska2022-log1pnorm-Lxn-Gfap",
    "arc-lutomska2022-log1pnorm-Lxn-Gja1",
    "arc-lutomska2022-log1pnorm-Lxn-Gli1",
    "arc-lutomska2022-log1pnorm-Lxn-Glul",
    "arc-lutomska2022-log1pnorm-Lxn-Hacd2",
    "arc-lutomska2022-log1pnorm-Lxn-Hadhb",
    "arc-lutomska2022-log1pnorm-Lxn-Hepacam",
    "arc-lutomska2022-log1pnorm-Lxn-Htra1",
    "arc-lutomska2022-log1pnorm-Lxn-Lcat",
    "arc-lutomska2022-log1pnorm-Lxn-Lpcat3",
    "arc-lutomska2022-log1pnorm-Lxn-Mfn1",
    "arc-lutomska2022-log1pnorm-Lxn-Mfn2",
    "arc-lutomska2022-log1pnorm-Lxn-Mgll",
    "arc-lutomska2022-log1pnorm-Lxn-Mief1",
    "arc-lutomska2022-log1pnorm-Lxn-Napepld",
    "arc-lutomska2022-log1pnorm-Lxn-Ndrg2",
    "arc-lutomska2022-log1pnorm-Lxn-Nfia",
    "arc-lutomska2022-log1pnorm-Lxn-Opa1",
    "arc-lutomska2022-log1pnorm-Lxn-Pex1",
    "arc-lutomska2022-log1pnorm-Lxn-Pex10",
    "arc-lutomska2022-log1pnorm-Lxn-Pex12",
    "arc-lutomska2022-log1pnorm-Lxn-Pex13",
    "arc-lutomska2022-log1pnorm-Lxn-Pex14",
    "arc-lutomska2022-log1pnorm-Lxn-Pex16",
    "arc-lutomska2022-log1pnorm-Lxn-Pex2",
    "arc-lutomska2022-log1pnorm-Lxn-Pex26",
    "arc-lutomska2022-log1pnorm-Lxn-Pex3",
    "arc-lutomska2022-log1pnorm-Lxn-Pex6",
    "arc-lutomska2022-log1pnorm-Lxn-Pla2g7",
    "arc-lutomska2022-log1pnorm-Lxn-Plcb1",
    "arc-lutomska2022-log1pnorm-Lxn-Pygb",
    "arc-lutomska2022-log1pnorm-Lxn-S100a6",
    "arc-lutomska2022-log1pnorm-Lxn-S100b",
    "arc-lutomska2022-log1pnorm-Lxn-Scd2",
    "arc-lutomska2022-log1pnorm-Lxn-Sgcd",
    "arc-lutomska2022-log1pnorm-Lxn-Slc1a2",
    "arc-lutomska2022-log1pnorm-Lxn-Slc1a3",
    "arc-lutomska2022-log1pnorm-Lxn-Slc38a1",
    "arc-lutomska2022-log1pnorm-Lxn-Slc6a11",
    "arc-lutomska2022-log1pnorm-Lxn-Slit1",
    "arc-lutomska2022-log1pnorm-Lxn-Slit2",
    "arc-lutomska2022-log1pnorm-Lxn-Sox9",
    "arc-lutomska2022-log1pnorm-Lxn-Tafa1",
    "arc-lutomska2022-log1pnorm-Lxn-Tkt",
    "arc-lutomska2022-log1pnorm-Gfap-Adcyap1r1",
    "arc-lutomska2022-log1pnorm-Gfap-Cckar",
    "arc-lutomska2022-log1pnorm-Gfap-Cckbr",
    "arc-lutomska2022-log1pnorm-Gfap-Cntfr",
    "arc-lutomska2022-log1pnorm-Gfap-Crhr1",
    "arc-lutomska2022-log1pnorm-Gfap-Esr1",
    "arc-lutomska2022-log1pnorm-Gfap-Galr2",
    "arc-lutomska2022-log1pnorm-Gfap-Ghr",
    "arc-lutomska2022-log1pnorm-Gfap-Gpr83",
    "arc-lutomska2022-log1pnorm-Gfap-Grpr",
    "arc-lutomska2022-log1pnorm-Gfap-Hcrtr2",
    "arc-lutomska2022-log1pnorm-Gfap-Kiss1r",
    "arc-lutomska2022-log1pnorm-Gfap-Mc1r",
    "arc-lutomska2022-log1pnorm-Gfap-Mc3r",
    "arc-lutomska2022-log1pnorm-Gfap-Mc4r",
    "arc-lutomska2022-log1pnorm-Gfap-Nmbr",
    "arc-lutomska2022-log1pnorm-Gfap-Nmur1",
    "arc-lutomska2022-log1pnorm-Gfap-Nmur2",
    "arc-lutomska2022-log1pnorm-Gfap-Npffr1",
    "arc-lutomska2022-log1pnorm-Gfap-Npffr2",
    "arc-lutomska2022-log1pnorm-Gfap-Npy1r",
    "arc-lutomska2022-log1pnorm-Gfap-Npy2r",
    "arc-lutomska2022-log1pnorm-Gfap-Npy5r",
    "arc-lutomska2022-log1pnorm-Gfap-Ntrk2",
    "arc-lutomska2022-log1pnorm-Gfap-Ntsr2",
    "arc-lutomska2022-log1pnorm-Gfap-Oprk1",
    "arc-lutomska2022-log1pnorm-Gfap-Oprm1",
    "arc-lutomska2022-log1pnorm-Gfap-Oxtr",
    "arc-lutomska2022-log1pnorm-Gfap-Prlhr",
    "arc-lutomska2022-log1pnorm-Gfap-Prlr",
    "arc-lutomska2022-log1pnorm-Gfap-Sstr1",
    "arc-lutomska2022-log1pnorm-Gfap-Sstr2",
    "arc-lutomska2022-log1pnorm-Gfap-Sstr3",
    "arc-lutomska2022-log1pnorm-Gfap-Tacr1",
    "arc-lutomska2022-log1pnorm-Gfap-Tacr3",
    "arc-lutomska2022-log1pnorm-Gfap-Trhr",
    "arc-lutomska2022-log1pnorm-Gfap-Vipr1",
    "arc-lutomska2022-log1pnorm-Gfap-Vipr2",
    "arc-lutomska2022-log1pnorm-Gfap-Gria1",
    "arc-lutomska2022-log1pnorm-Gfap-Gria2",
    "arc-lutomska2022-log1pnorm-Gfap-Gria3",
    "arc-lutomska2022-log1pnorm-Gfap-Gria4",
    "arc-lutomska2022-log1pnorm-Gfap-Grid1",
    "arc-lutomska2022-log1pnorm-Gfap-Grid2",
    "arc-lutomska2022-log1pnorm-Gfap-Grik1",
    "arc-lutomska2022-log1pnorm-Gfap-Grik2",
    "arc-lutomska2022-log1pnorm-Gfap-Grik3",
    "arc-lutomska2022-log1pnorm-Gfap-Grik4",
    "arc-lutomska2022-log1pnorm-Gfap-Grik5",
    "arc-lutomska2022-log1pnorm-Gfap-Grin1",
    "arc-lutomska2022-log1pnorm-Gfap-Grin2a",
    "arc-lutomska2022-log1pnorm-Gfap-Grin2b",
    "arc-lutomska2022-log1pnorm-Gfap-Grin2c",
    "arc-lutomska2022-log1pnorm-Gfap-Grin2d",
    "arc-lutomska2022-log1pnorm-Gfap-Grin3a",
    "arc-lutomska2022-log1pnorm-Gfap-Grin3b",
    "arc-lutomska2022-log1pnorm-Gfap-Grm1",
    "arc-lutomska2022-log1pnorm-Gfap-Grm5",
    "arc-lutomska2022-log1pnorm-Gfap-Grm2",
    "arc-lutomska2022-log1pnorm-Gfap-Grm3",
    "arc-lutomska2022-log1pnorm-Gfap-Grm4",
    "arc-lutomska2022-log1pnorm-Gfap-Grm7",
    "arc-lutomska2022-log1pnorm-Gfap-Grm8",
    "arc-lutomska2022-log1pnorm-Gfap-Gabra1",
    "arc-lutomska2022-log1pnorm-Gfap-Gabra2",
    "arc-lutomska2022-log1pnorm-Gfap-Gabra3",
    "arc-lutomska2022-log1pnorm-Gfap-Gabra4",
    "arc-lutomska2022-log1pnorm-Gfap-Gabra5",
    "arc-lutomska2022-log1pnorm-Gfap-Gabra6",
    "arc-lutomska2022-log1pnorm-Gfap-Gabrb1",
    "arc-lutomska2022-log1pnorm-Gfap-Gabrb2",
    "arc-lutomska2022-log1pnorm-Gfap-Gabrb3",
    "arc-lutomska2022-log1pnorm-Gfap-Gabrg1",
    "arc-lutomska2022-log1pnorm-Gfap-Gabrg2",
    "arc-lutomska2022-log1pnorm-Gfap-Gabrg3",
    "arc-lutomska2022-log1pnorm-Gfap-Gabrd",
    "arc-lutomska2022-log1pnorm-Gfap-Gabre",
    "arc-lutomska2022-log1pnorm-Gfap-Gabrq",
    "arc-lutomska2022-log1pnorm-Gfap-Gabrr2",
    "arc-lutomska2022-log1pnorm-Gfap-Gabrr3",
    "arc-lutomska2022-log1pnorm-Gfap-Gabbr1",
    "arc-lutomska2022-log1pnorm-Gfap-Gabbr2",
    "arc-lutomska2022-log1pnorm-Gfap-Drd2",
    "arc-lutomska2022-log1pnorm-Gfap-Drd3",
    "arc-lutomska2022-log1pnorm-Gfap-Htr1b",
    "arc-lutomska2022-log1pnorm-Gfap-Htr1f",
    "arc-lutomska2022-log1pnorm-Gfap-Htr2a",
    "arc-lutomska2022-log1pnorm-Gfap-Htr2b",
    "arc-lutomska2022-log1pnorm-Gfap-Htr2c",
    "arc-lutomska2022-log1pnorm-Gfap-Htr3b",
    "arc-lutomska2022-log1pnorm-Gfap-Htr4",
    "arc-lutomska2022-log1pnorm-Gfap-Htr5a",
    "arc-lutomska2022-log1pnorm-Gfap-Htr5b",
    "arc-lutomska2022-log1pnorm-Gfap-Htr6",
    "arc-lutomska2022-log1pnorm-Gfap-Htr7",
    "arc-lutomska2022-log1pnorm-Gfap-Gnai1",
    "arc-lutomska2022-log1pnorm-Gfap-Gnai2",
    "arc-lutomska2022-log1pnorm-Gfap-Gnai3",
    "arc-lutomska2022-log1pnorm-Gfap-Gnao1",
    "arc-lutomska2022-log1pnorm-Gfap-Gnaz",
    "arc-lutomska2022-log1pnorm-Gfap-Abcd1",
    "arc-lutomska2022-log1pnorm-Gfap-Abcd2",
    "arc-lutomska2022-log1pnorm-Gfap-Abcd3",
    "arc-lutomska2022-log1pnorm-Gfap-Acaa2",
    "arc-lutomska2022-log1pnorm-Gfap-Acox1",
    "arc-lutomska2022-log1pnorm-Gfap-Agt",
    "arc-lutomska2022-log1pnorm-Gfap-Aldh1a1",
    "arc-lutomska2022-log1pnorm-Gfap-Aldh1l1",
    "arc-lutomska2022-log1pnorm-Gfap-Aldoc",
    "arc-lutomska2022-log1pnorm-Gfap-Apoe",
    "arc-lutomska2022-log1pnorm-Gfap-Aqp4",
    "arc-lutomska2022-log1pnorm-Gfap-Ckb",
    "arc-lutomska2022-log1pnorm-Gfap-Cnr2",
    "arc-lutomska2022-log1pnorm-Gfap-Cst3",
    "arc-lutomska2022-log1pnorm-Gfap-Dagla",
    "arc-lutomska2022-log1pnorm-Gfap-Daglb",
    "arc-lutomska2022-log1pnorm-Gfap-Decr2",
    "arc-lutomska2022-log1pnorm-Gfap-Dnm1",
    "arc-lutomska2022-log1pnorm-Gfap-Ech1",
    "arc-lutomska2022-log1pnorm-Gfap-Egfr",
    "arc-lutomska2022-log1pnorm-Gfap-Eno1",
    "arc-lutomska2022-log1pnorm-Gfap-Faah",
    "arc-lutomska2022-log1pnorm-Gfap-Fgfr3",
    "arc-lutomska2022-log1pnorm-Gfap-Fis1",
    "arc-lutomska2022-log1pnorm-Gfap-Fos",
    "arc-lutomska2022-log1pnorm-Gfap-Fth1",
    "arc-lutomska2022-log1pnorm-Gfap-Ftl1",
    "arc-lutomska2022-log1pnorm-Gfap-Gja1",
    "arc-lutomska2022-log1pnorm-Gfap-Gli1",
    "arc-lutomska2022-log1pnorm-Gfap-Glul",
    "arc-lutomska2022-log1pnorm-Gfap-Hacd2",
    "arc-lutomska2022-log1pnorm-Gfap-Hadhb",
    "arc-lutomska2022-log1pnorm-Gfap-Hepacam",
    "arc-lutomska2022-log1pnorm-Gfap-Htra1",
    "arc-lutomska2022-log1pnorm-Gfap-Lcat",
    "arc-lutomska2022-log1pnorm-Gfap-Lpcat3",
    "arc-lutomska2022-log1pnorm-Gfap-Lxn",
    "arc-lutomska2022-log1pnorm-Gfap-Mfn1",
    "arc-lutomska2022-log1pnorm-Gfap-Mfn2",
    "arc-lutomska2022-log1pnorm-Gfap-Mgll",
    "arc-lutomska2022-log1pnorm-Gfap-Mief1",
    "arc-lutomska2022-log1pnorm-Gfap-Napepld",
    "arc-lutomska2022-log1pnorm-Gfap-Ndrg2",
    "arc-lutomska2022-log1pnorm-Gfap-Nfia",
    "arc-lutomska2022-log1pnorm-Gfap-Opa1",
    "arc-lutomska2022-log1pnorm-Gfap-Pex1",
    "arc-lutomska2022-log1pnorm-Gfap-Pex10",
    "arc-lutomska2022-log1pnorm-Gfap-Pex12",
    "arc-lutomska2022-log1pnorm-Gfap-Pex13",
    "arc-lutomska2022-log1pnorm-Gfap-Pex14",
    "arc-lutomska2022-log1pnorm-Gfap-Pex16",
    "arc-lutomska2022-log1pnorm-Gfap-Pex2",
    "arc-lutomska2022-log1pnorm-Gfap-Pex26",
    "arc-lutomska2022-log1pnorm-Gfap-Pex3",
    "arc-lutomska2022-log1pnorm-Gfap-Pex6",
    "arc-lutomska2022-log1pnorm-Gfap-Pla2g7",
    "arc-lutomska2022-log1pnorm-Gfap-Plcb1",
    "arc-lutomska2022-log1pnorm-Gfap-Pygb",
    "arc-lutomska2022-log1pnorm-Gfap-S100a6",
    "arc-lutomska2022-log1pnorm-Gfap-S100b",
    "arc-lutomska2022-log1pnorm-Gfap-Scd2",
    "arc-lutomska2022-log1pnorm-Gfap-Sgcd",
    "arc-lutomska2022-log1pnorm-Gfap-Slc1a2",
    "arc-lutomska2022-log1pnorm-Gfap-Slc1a3",
    "arc-lutomska2022-log1pnorm-Gfap-Slc38a1",
    "arc-lutomska2022-log1pnorm-Gfap-Slc6a11",
    "arc-lutomska2022-log1pnorm-Gfap-Slit1",
    "arc-lutomska2022-log1pnorm-Gfap-Slit2",
    "arc-lutomska2022-log1pnorm-Gfap-Sox9",
    "arc-lutomska2022-log1pnorm-Gfap-Tafa1",
    "arc-lutomska2022-log1pnorm-Gfap-Tkt",
    "arc-lutomska2022-log1pnorm-Fos-Adcyap1r1",
    "arc-lutomska2022-log1pnorm-Fos-Cckar",
    "arc-lutomska2022-log1pnorm-Fos-Cckbr",
    "arc-lutomska2022-log1pnorm-Fos-Cntfr",
    "arc-lutomska2022-log1pnorm-Fos-Crhr1",
    "arc-lutomska2022-log1pnorm-Fos-Esr1",
    "arc-lutomska2022-log1pnorm-Fos-Galr2",
    "arc-lutomska2022-log1pnorm-Fos-Ghr",
    "arc-lutomska2022-log1pnorm-Fos-Gpr83",
    "arc-lutomska2022-log1pnorm-Fos-Grpr",
    "arc-lutomska2022-log1pnorm-Fos-Hcrtr2",
    "arc-lutomska2022-log1pnorm-Fos-Kiss1r",
    "arc-lutomska2022-log1pnorm-Fos-Mc1r",
    "arc-lutomska2022-log1pnorm-Fos-Mc3r",
    "arc-lutomska2022-log1pnorm-Fos-Mc4r",
    "arc-lutomska2022-log1pnorm-Fos-Nmbr",
    "arc-lutomska2022-log1pnorm-Fos-Nmur1",
    "arc-lutomska2022-log1pnorm-Fos-Nmur2",
    "arc-lutomska2022-log1pnorm-Fos-Npffr1",
    "arc-lutomska2022-log1pnorm-Fos-Npffr2",
    "arc-lutomska2022-log1pnorm-Fos-Npy1r",
    "arc-lutomska2022-log1pnorm-Fos-Npy2r",
    "arc-lutomska2022-log1pnorm-Fos-Npy5r",
    "arc-lutomska2022-log1pnorm-Fos-Ntrk2",
    "arc-lutomska2022-log1pnorm-Fos-Ntsr2",
    "arc-lutomska2022-log1pnorm-Fos-Oprk1",
    "arc-lutomska2022-log1pnorm-Fos-Oprm1",
    "arc-lutomska2022-log1pnorm-Fos-Oxtr",
    "arc-lutomska2022-log1pnorm-Fos-Prlhr",
    "arc-lutomska2022-log1pnorm-Fos-Prlr",
    "arc-lutomska2022-log1pnorm-Fos-Sstr1",
    "arc-lutomska2022-log1pnorm-Fos-Sstr2",
    "arc-lutomska2022-log1pnorm-Fos-Sstr3",
    "arc-lutomska2022-log1pnorm-Fos-Tacr1",
    "arc-lutomska2022-log1pnorm-Fos-Tacr3",
    "arc-lutomska2022-log1pnorm-Fos-Trhr",
    "arc-lutomska2022-log1pnorm-Fos-Vipr1",
    "arc-lutomska2022-log1pnorm-Fos-Vipr2",
    "arc-lutomska2022-log1pnorm-Fos-Gria1",
    "arc-lutomska2022-log1pnorm-Fos-Gria2",
    "arc-lutomska2022-log1pnorm-Fos-Gria3",
    "arc-lutomska2022-log1pnorm-Fos-Gria4",
    "arc-lutomska2022-log1pnorm-Fos-Grid1",
    "arc-lutomska2022-log1pnorm-Fos-Grid2",
    "arc-lutomska2022-log1pnorm-Fos-Grik1",
    "arc-lutomska2022-log1pnorm-Fos-Grik2",
    "arc-lutomska2022-log1pnorm-Fos-Grik3",
    "arc-lutomska2022-log1pnorm-Fos-Grik4",
    "arc-lutomska2022-log1pnorm-Fos-Grik5",
    "arc-lutomska2022-log1pnorm-Fos-Grin1",
    "arc-lutomska2022-log1pnorm-Fos-Grin2a",
    "arc-lutomska2022-log1pnorm-Fos-Grin2b",
    "arc-lutomska2022-log1pnorm-Fos-Grin2c",
    "arc-lutomska2022-log1pnorm-Fos-Grin2d",
    "arc-lutomska2022-log1pnorm-Fos-Grin3a",
    "arc-lutomska2022-log1pnorm-Fos-Grin3b",
    "arc-lutomska2022-log1pnorm-Fos-Grm1",
    "arc-lutomska2022-log1pnorm-Fos-Grm5",
    "arc-lutomska2022-log1pnorm-Fos-Grm2",
    "arc-lutomska2022-log1pnorm-Fos-Grm3",
    "arc-lutomska2022-log1pnorm-Fos-Grm4",
    "arc-lutomska2022-log1pnorm-Fos-Grm7",
    "arc-lutomska2022-log1pnorm-Fos-Grm8",
    "arc-lutomska2022-log1pnorm-Fos-Gabra1",
    "arc-lutomska2022-log1pnorm-Fos-Gabra2",
    "arc-lutomska2022-log1pnorm-Fos-Gabra3",
    "arc-lutomska2022-log1pnorm-Fos-Gabra4",
    "arc-lutomska2022-log1pnorm-Fos-Gabra5",
    "arc-lutomska2022-log1pnorm-Fos-Gabra6",
    "arc-lutomska2022-log1pnorm-Fos-Gabrb1",
    "arc-lutomska2022-log1pnorm-Fos-Gabrb2",
    "arc-lutomska2022-log1pnorm-Fos-Gabrb3",
    "arc-lutomska2022-log1pnorm-Fos-Gabrg1",
    "arc-lutomska2022-log1pnorm-Fos-Gabrg2",
    "arc-lutomska2022-log1pnorm-Fos-Gabrg3",
    "arc-lutomska2022-log1pnorm-Fos-Gabrd",
    "arc-lutomska2022-log1pnorm-Fos-Gabre",
    "arc-lutomska2022-log1pnorm-Fos-Gabrq",
    "arc-lutomska2022-log1pnorm-Fos-Gabrr2",
    "arc-lutomska2022-log1pnorm-Fos-Gabrr3",
    "arc-lutomska2022-log1pnorm-Fos-Gabbr1",
    "arc-lutomska2022-log1pnorm-Fos-Gabbr2",
    "arc-lutomska2022-log1pnorm-Fos-Drd2",
    "arc-lutomska2022-log1pnorm-Fos-Drd3",
    "arc-lutomska2022-log1pnorm-Fos-Htr1b",
    "arc-lutomska2022-log1pnorm-Fos-Htr1f",
    "arc-lutomska2022-log1pnorm-Fos-Htr2a",
    "arc-lutomska2022-log1pnorm-Fos-Htr2b",
    "arc-lutomska2022-log1pnorm-Fos-Htr2c",
    "arc-lutomska2022-log1pnorm-Fos-Htr3b",
    "arc-lutomska2022-log1pnorm-Fos-Htr4",
    "arc-lutomska2022-log1pnorm-Fos-Htr5a",
    "arc-lutomska2022-log1pnorm-Fos-Htr5b",
    "arc-lutomska2022-log1pnorm-Fos-Htr6",
    "arc-lutomska2022-log1pnorm-Fos-Htr7",
    "arc-lutomska2022-log1pnorm-Fos-Gnai1",
    "arc-lutomska2022-log1pnorm-Fos-Gnai2",
    "arc-lutomska2022-log1pnorm-Fos-Gnai3",
    "arc-lutomska2022-log1pnorm-Fos-Gnao1",
    "arc-lutomska2022-log1pnorm-Fos-Gnaz",
    "arc-lutomska2022-log1pnorm-Fos-Abcd1",
    "arc-lutomska2022-log1pnorm-Fos-Abcd2",
    "arc-lutomska2022-log1pnorm-Fos-Abcd3",
    "arc-lutomska2022-log1pnorm-Fos-Acaa2",
    "arc-lutomska2022-log1pnorm-Fos-Acox1",
    "arc-lutomska2022-log1pnorm-Fos-Agt",
    "arc-lutomska2022-log1pnorm-Fos-Aldh1a1",
    "arc-lutomska2022-log1pnorm-Fos-Aldh1l1",
    "arc-lutomska2022-log1pnorm-Fos-Aldoc",
    "arc-lutomska2022-log1pnorm-Fos-Apoe",
    "arc-lutomska2022-log1pnorm-Fos-Aqp4",
    "arc-lutomska2022-log1pnorm-Fos-Ckb",
    "arc-lutomska2022-log1pnorm-Fos-Cnr2",
    "arc-lutomska2022-log1pnorm-Fos-Cst3",
    "arc-lutomska2022-log1pnorm-Fos-Dagla",
    "arc-lutomska2022-log1pnorm-Fos-Daglb",
    "arc-lutomska2022-log1pnorm-Fos-Decr2",
    "arc-lutomska2022-log1pnorm-Fos-Dnm1",
    "arc-lutomska2022-log1pnorm-Fos-Ech1",
    "arc-lutomska2022-log1pnorm-Fos-Egfr",
    "arc-lutomska2022-log1pnorm-Fos-Eno1",
    "arc-lutomska2022-log1pnorm-Fos-Faah",
    "arc-lutomska2022-log1pnorm-Fos-Fgfr3",
    "arc-lutomska2022-log1pnorm-Fos-Fis1",
    "arc-lutomska2022-log1pnorm-Fos-Fth1",
    "arc-lutomska2022-log1pnorm-Fos-Ftl1",
    "arc-lutomska2022-log1pnorm-Fos-Gfap",
    "arc-lutomska2022-log1pnorm-Fos-Gja1",
    "arc-lutomska2022-log1pnorm-Fos-Gli1",
    "arc-lutomska2022-log1pnorm-Fos-Glul",
    "arc-lutomska2022-log1pnorm-Fos-Hacd2",
    "arc-lutomska2022-log1pnorm-Fos-Hadhb",
    "arc-lutomska2022-log1pnorm-Fos-Hepacam",
    "arc-lutomska2022-log1pnorm-Fos-Htra1",
    "arc-lutomska2022-log1pnorm-Fos-Lcat",
    "arc-lutomska2022-log1pnorm-Fos-Lpcat3",
    "arc-lutomska2022-log1pnorm-Fos-Lxn",
    "arc-lutomska2022-log1pnorm-Fos-Mfn1",
    "arc-lutomska2022-log1pnorm-Fos-Mfn2",
    "arc-lutomska2022-log1pnorm-Fos-Mgll",
    "arc-lutomska2022-log1pnorm-Fos-Mief1",
    "arc-lutomska2022-log1pnorm-Fos-Napepld",
    "arc-lutomska2022-log1pnorm-Fos-Ndrg2",
    "arc-lutomska2022-log1pnorm-Fos-Nfia",
    "arc-lutomska2022-log1pnorm-Fos-Opa1",
    "arc-lutomska2022-log1pnorm-Fos-Pex1",
    "arc-lutomska2022-log1pnorm-Fos-Pex10",
    "arc-lutomska2022-log1pnorm-Fos-Pex12",
    "arc-lutomska2022-log1pnorm-Fos-Pex13",
    "arc-lutomska2022-log1pnorm-Fos-Pex14",
    "arc-lutomska2022-log1pnorm-Fos-Pex16",
    "arc-lutomska2022-log1pnorm-Fos-Pex2",
    "arc-lutomska2022-log1pnorm-Fos-Pex26",
    "arc-lutomska2022-log1pnorm-Fos-Pex3",
    "arc-lutomska2022-log1pnorm-Fos-Pex6",
    "arc-lutomska2022-log1pnorm-Fos-Pla2g7",
    "arc-lutomska2022-log1pnorm-Fos-Plcb1",
    "arc-lutomska2022-log1pnorm-Fos-Pygb",
    "arc-lutomska2022-log1pnorm-Fos-S100a6",
    "arc-lutomska2022-log1pnorm-Fos-S100b",
    "arc-lutomska2022-log1pnorm-Fos-Scd2",
    "arc-lutomska2022-log1pnorm-Fos-Sgcd",
    "arc-lutomska2022-log1pnorm-Fos-Slc1a2",
    "arc-lutomska2022-log1pnorm-Fos-Slc1a3",
    "arc-lutomska2022-log1pnorm-Fos-Slc38a1",
    "arc-lutomska2022-log1pnorm-Fos-Slc6a11",
    "arc-lutomska2022-log1pnorm-Fos-Slit1",
    "arc-lutomska2022-log1pnorm-Fos-Slit2",
    "arc-lutomska2022-log1pnorm-Fos-Sox9",
    "arc-lutomska2022-log1pnorm-Fos-Tafa1",
    "arc-lutomska2022-log1pnorm-Fos-Tkt"
)
purrr::walk2(n_corrs, p_corrs, save_my_plot, type = "stat-corr-plt", h = 30, asp = .229)
```

```{r plot-corrmatrix, fig.height=140, fig.asp=1.854, fig.align="center", fig.cap="Correlation matrix of the metadata QC-metrics and the gene set of interest: neuromediators/neuropeptides receptors, metabolic enzymes and other markers of astocytic functional states"}
plt_grp_ggcorrmat <- grouped_ggcorrmat(
  ## arguments relevant for `ggcorrmat()`
  data = df, type = "r",
  cor.vars = c(nCount_RNA:log10GenesPerUMI, Adcyap1r1:Tkt),
  grouping.var = expbtch,
  ## arguments relevant for `combine_plots()`
  plotgrid.args = list(nrow = 3),
  annotation.args = list(
    tag_levels = "a",
    title = "Relationship between astrocytic functional states markers, neuromediators \nand neuropeptides receptors, metabolic enzymes and the metadata QC-metrics",
    caption = "Dataset: subset of astrocytes from the Arcuate nucleus of the mouse hypothalamus in progression of High Fat Diet (Lutomska et al., 2022)"
  )
)

plt_grp_ggcorrmat
```

```{r save-plt-corrmatrix}
save_my_plot(
  name = bioproject,
  plt = plt_grp_ggcorrmat,
  type = "stat-corrmatrix-plt",
  h = 140,
  asp = .54
)
```


## Session information

```{r session-info, cache = FALSE}
sI <- sessioninfo::session_info()
sI$loadedOnly <- NULL
print(sI, locale=FALSE)
```